image: golang:1.18.3-alpine

stages:
  - test

test-backend:
  stage: test
  script:
    - CGO_ENABLED=0 go test ./tests/... -coverprofile=coverage-report.out
    - go tool cover -html=coverage-report.out -o coverage-report.html
    - go tool cover -func=coverage-report.out
  artifacts:
    paths:
      - coverage-report.html
    expire_in: 1 days
  coverage: "/\\(statements\\)\\s+\\d+.?\\d+%/"